title: 一瓶论语

email: abolybook@gmail.com

description: >
  开源《论语》读本，传统内涵，现代价值

url: "http://abolybook.org"
baseurl: "" # the subpath of your site, e.g. /blog

github_username: abolybook

github_project: aboly

# Build settings
markdown: kramdown

plugins:
  - jemoji
